server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = /sw.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location ~* \.webmanifest$ {
        add_header Content-Type application/manifest+json;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|svg|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
